// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ResizeImages(arg1:number,arg2:number,arg3:Array<string>):Promise<Array<string>>;

export function SaveImages(arg1:Array<string>):Promise<string>;
