// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchImages(arg1) {
  return window['go']['main']['App']['FetchImages'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResizeImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeImages'](arg1, arg2, arg3, arg4);
}

export function SaveImages(arg1) {
  return window['go']['main']['App']['SaveImages'](arg1);
}
